# Generated by Django 5.2.4 on 2025-07-15 22:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.BooleanField(default=True)),
                ('rua', models.CharField(max_length=100)),
                ('predio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel', models.CharField(max_length=50)),
                ('apartamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_validade', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('data_fabricacao', models.DateField(default=datetime.datetime.now)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.armazem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
